# Generated by Django 5.2.3 on 2025-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(choices=[('BCT001', 'Math'), ('BCT002', 'Science'), ('BCT003', 'English'), ('BCT004', 'History'), ('BCT005', 'Geography'), ('BCT006', 'Geography')], default='N/A', max_length=20, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.CharField(choices=[('BCT001', 'Math'), ('BCT002', 'Science'), ('BCT003', 'English'), ('BCT004', 'History'), ('BCT005', 'Geography'), ('BCT006', 'Geography')], default='N/A', max_length=20, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCT', 'Bachelor of Computer Engineering'), ('BCA', 'Bachelor of Computer Application'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=20, null=True),
        ),
    ]
