# Generated by Django 5.2.3 on 2025-06-18 14:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='join_data',
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Join date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Question description'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/question/', verbose_name='Question file'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='remark',
            field=models.CharField(max_length=100, verbose_name='Remark'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Assignment title'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('VIDEO', 'Video'), ('PDF', 'PDF'), ('PPT', 'PowerPoint'), ('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='N/A', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='File upload'),
        ),
        migrations.AlterField(
            model_name='material',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Upload date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCA', 'Bachelor of Computer Application'), ('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering')], default='N/A', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_no',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
