# Generated by Django 5.2.3 on 2025-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignment_subject_alter_material_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('notes', 'Notes'), ('video', 'Video'), ('pdf', 'Pdf'), ('ppt', 'Ppt')], default='N\\A', max_length=20, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='material', verbose_name='select_file'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, choices=[('BCT', 'Bachelor of Computer Engineering'), ('BEI', 'Bachelor of Electronics and Information'), ('BCE', 'Bachelor of Civil Engineering'), ('BCA', 'Bachelor of Computer Application')], default='N/A', max_length=20, null=True),
        ),
    ]
